import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"

import './globals.css'

import TwitchIcon from '@/components/icons/twitch'
import { Button } from '@/components/ui/button'
import Navigation from '@/components/navigation'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <SignedIn>
            <Navigation />

            {children}
          </SignedIn>

          <SignedOut>
            <div className="flex items-center justify-center min-h-screen">
              <SignInButton>
                <Button variant="twitch">
                  <TwitchIcon />
                  Sign In With Twitch
                </Button>
              </SignInButton>
            </div>
          </SignedOut>

          <Analytics />
          <SpeedInsights />
        </body>
      </html>
    </ClerkProvider>
  )
}